[versions]
kotlin = "2.3.0"
neoforge = "21.1.93"
neoforge-range = "[21,)"
moddev = "2.0.74"
parchment = "2024.11.17"
minecraft = "1.21.1"
minecraft-range = "[1.21.1]"
mod-publish = "1.0.0"

kff = "5.11.0"

[libraries]
kotlin-neoforge = { module = "thedarkcolour:kotlinforforge-neoforge", version.ref = "kff" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
moddev = { id = "net.neoforged.moddev", version.ref = "moddev" }
mod-publish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish" }